name: Hello DevOps

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Afficher un message
        run: echo "👋 Bien joué Hillel ! Ton pipeline tourne."

UW PICO 5.09  File: .github/workflows/hello.yml



